# For information about what configuration options are available, see
# https://slashdeploy.io/docs"
---
environments:
  production:
    continuous_delivery: &cd
      ref: refs/heads/master
      required_contexts:
        - "ci/circleci: test"
        - "ci/circleci: docker_image"
  staging:
    continuous_delivery:
      <<: *cd
