# when updating this file, follow instructions in ./README.md to push the new image
FROM circleci/node:10.9.0

RUN sudo npm install -g yarn@1.9.4
ENV PATH "$PATH:/root/.yarn/bin/:/usr/local/bin"

CMD [ "node" ]
